name: Benchmark and push to CodePerf

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run Benchmark
        run: go test -bench=BenchmarkFib10 -cpuprofile profile.out
      - name: Get CodePerf Go utility
        run: bash <(curl -s https://raw.githubusercontent.com/codeperfio/pprof-exporter/main/get.sh)
      - name: Upload profile data to CodePerf
        run: ./pprof-exporter --bench BenchmarkFib10 profile.out
